version: '3'
services:
  server:
    build: .
    image: phunh/cloudcomputinggroup196:latest
    container_name: cloudcomputinggroup196
    depends_on:
      - "mongodb"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/booksData
    ports:
      - "3000:3030" # HOST:CONTAINER
    restart: always
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/:/data/db
    ports:
      - "27017"

